import type { Metadata } from 'next';
import { Gabarito } from 'next/font/google';
import './globals.css';
import Providers from '@/lib/provider';

import Navbar from '@/components/Navbar';

const gabarito = Gabarito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gabarito.className} bg-color-dark`}>
        <Providers>
          <Navbar />
          <div className="xl:pt-[5rem] lg:pt-[6rem] md:pt-[5rem] pt-[10rem] md:mx-20 mx-5">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
